name: Project Maintenance
on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily at 3 AM UTC (8:30 AM Sri Lanka)
  workflow_dispatch:        # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update maintenance log
        run: |
          mkdir -p .github/logs
          echo "Last maintenance check: $(date)" > .github/logs/system-status.log

      - name: Commit and push changes
        run: |
          git config --global user.name "chenukadanith"
          git config --global user.email "chenukadanith@gmail.com"
          git add -f .github/logs/system-status.log
          git commit -m "System check: $(date)" || echo "No changes to commit"
          git push
