name: Project Maintenance
on:
  schedule:
    # Dynamic scheduling - runs at varied times throughout the day
    - cron: '0 0,3,6,9,12,15,18,21 * * *'  # Runs 8 times per day (every 3 hours)
    - cron: '30 1,4,7,10,13,16,19,22 * * *' # Runs 8 times per day offset
    - cron: '15 2,5,8,11,14,17,20,23 * * *' # Runs 8 times per day offset
  workflow_dispatch:          # Allows manual trigger
  push:
    branches: [ main ]        # Also runs on push to main

permissions:
  contents: write
  actions: write

jobs:
  maintain-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git configuration
        run: |
          git config --global user.name "chenukadanith"
          git config --global user.email "chenukadanith@gmail.com"

      - name: Determine if commit should be made
        id: should_commit
        run: |
          # Generate random number between 1-100
          CHANCE=$((RANDOM % 100 + 1))
          
          # Get day of week (0-6, 0 is Sunday)
          DAY_OF_WEEK=$(date +%u)
          
          # 75% chance to commit (1-75 = yes, 76-100 = no)
          # Slightly higher chance on weekdays (Mon-Fri)
          if [ $DAY_OF_WEEK -le 5 ]; then
            # Weekday: 80% chance
            if [ $CHANCE -le 80 ]; then
              echo "should_commit=true" >> $GITHUB_OUTPUT
            else
              echo "should_commit=false" >> $GITHUB_OUTPUT
            fi
          else
            # Weekend: 65% chance (more realistic pattern)
            if [ $CHANCE -le 65 ]; then
              echo "should_commit=true" >> $GITHUB_OUTPUT
            else
              echo "should_commit=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          echo "Commit decision: $([ $CHANCE -le 75 ] && echo 'YES' || echo 'NO') (rolled $CHANCE)"

      - name: Create activity logs
        if: steps.should_commit.outputs.should_commit == 'true'
        run: |
          # Create directories
          mkdir -p logs/daily logs/hourly stats
          
          # Timestamp variables
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          TODAY=$(date +'%Y-%m-%d')
          HOUR=$(date +'%H')
          
          # Daily log
          echo "=== Daily Maintenance Log ===" > logs/daily/log-$TODAY.txt
          echo "Date: $TIMESTAMP" >> logs/daily/log-$TODAY.txt
          echo "Status: System operational" >> logs/daily/log-$TODAY.txt
          echo "" >> logs/daily/log-$TODAY.txt
          echo "Checks performed:" >> logs/daily/log-$TODAY.txt
          echo "- Repository integrity: OK" >> logs/daily/log-$TODAY.txt
          echo "- Workflow health: OK" >> logs/daily/log-$TODAY.txt
          echo "- Storage capacity: $(df -h . | tail -1 | awk '{print $5}') used" >> logs/daily/log-$TODAY.txt
          
          # Hourly log
          echo "Hourly check: $TIMESTAMP" > logs/hourly/check-$TODAY-$HOUR.txt
          echo "Memory: $(free -h | grep Mem | awk '{print $3 "/" $2}')" >> logs/hourly/check-$TODAY-$HOUR.txt
          echo "Workflow run: #${{ github.run_number }}" >> logs/hourly/check-$TODAY-$HOUR.txt

      - name: Update statistics
        if: steps.should_commit.outputs.should_commit == 'true'
        run: |
          TODAY=$(date +'%Y-%m-%d')
          TOTAL_RUNS=${{ github.run_number }}
          
          # Create statistics file
          cat > stats/activity-summary.md << EOF
          # Project Activity Statistics
          
          **Last Updated:** $(date +'%Y-%m-%d %H:%M:%S UTC')
          
          ## Metrics
          - Total Workflow Runs: $TOTAL_RUNS
          - Current Date: $TODAY
          - Repository Status: Active ✅
          - Automation Status: Running ✅
          
          ## Recent Activity
          - Last check: $(date +'%H:%M:%S UTC')
          - Next scheduled: $(date -d '+3 hours' +'%H:%M:%S UTC')
          
          ---
          *Maintenance system v2.0*
          EOF

      - name: Generate random activity file
        if: steps.should_commit.outputs.should_commit == 'true'
        run: |
          # Create varied content to ensure unique commits
          RANDOM_NUM=$RANDOM
          TODAY=$(date +'%Y-%m-%d')
          
          mkdir -p activity
          cat > activity/latest.txt << EOF
          Activity ID: $RANDOM_NUM
          Timestamp: $(date +'%Y-%m-%d %H:%M:%S')
          Runner: ${{ runner.os }}
          Workflow: ${{ github.workflow }}
          Run Number: ${{ github.run_number }}
          Random Hash: $(echo $RANDOM | md5sum | head -c 16)
          EOF

      - name: Cleanup old logs (keep last 7 days)
        if: steps.should_commit.outputs.should_commit == 'true'
        run: |
          # Remove hourly logs older than 7 days
          find logs/hourly -name "*.txt" -mtime +7 -delete 2>/dev/null || true
          
          # Remove daily logs older than 30 days
          find logs/daily -name "*.txt" -mtime +30 -delete 2>/dev/null || true

      - name: Commit and push changes
        if: steps.should_commit.outputs.should_commit == 'true'
        run: |
          # Add all changes
          git add -A
          
          # Always create a change to ensure commit happens
          echo "Last run: $(date)" >> .maintenance-heartbeat
          git add .maintenance-heartbeat
          
          # Generate random issue number between 1-999
          ISSUE_NUM=$((RANDOM % 999 + 1))
          
          # Array of realistic commit message prefixes
          PREFIXES=(
            "Fix issue"
            "Resolve bug"
            "Update"
            "Improve"
            "Refactor"
            "Optimize"
            "Enhance"
            "Patch"
            "Address issue"
            "Handle"
            "Correct"
            "Adjust"
            "Modify"
            "Fix edge case in"
            "Fix security issue"
            "Performance fix for"
            "Hotfix"
            "Critical fix"
            "Fix regression in"
            "Fix memory leak in"
          )
          
          # Array of realistic commit message subjects
          SUBJECTS=(
            "authentication flow"
            "data validation"
            "error handling"
            "API response"
            "database connection"
            "user permissions"
            "cache invalidation"
            "file upload"
            "search functionality"
            "notification system"
            "logging mechanism"
            "session management"
            "input sanitization"
            "rate limiting"
            "webhook processing"
            "email delivery"
            "payment processing"
            "user profile"
            "configuration settings"
            "background jobs"
          )
          
          # Randomly select prefix and subject
          PREFIX=${PREFIXES[$RANDOM % ${#PREFIXES[@]}]}
          SUBJECT=${SUBJECTS[$RANDOM % ${#SUBJECTS[@]}]}
          
          # Generate commit message (50% chance to include issue number)
          if [ $((RANDOM % 2)) -eq 0 ]; then
            COMMIT_MSG="$PREFIX #$ISSUE_NUM"
          else
            COMMIT_MSG="$PREFIX $SUBJECT"
          fi
          
          # Commit changes
          git commit -m "$COMMIT_MSG"
          
          # Push to repository
          git push origin main

      - name: Workflow summary
        run: |
          if [ "${{ steps.should_commit.outputs.should_commit }}" == "true" ]; then
            echo "## ✅ Commit Created" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Time:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
            echo "- **Run:** #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Status:** Active" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ⏭️ Commit Skipped" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Time:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
            echo "- **Reason:** Random selection (more natural pattern)" >> $GITHUB_STEP_SUMMARY
          fi
